#macro SCRIBBLE_ANIM_DEFAULT_WAVE_SIZE           4
#macro SCRIBBLE_ANIM_DEFAULT_WAVE_FREQUENCY      50
#macro SCRIBBLE_ANIM_DEFAULT_WAVE_SPEED          0.2

#macro SCRIBBLE_ANIM_DEFAULT_SHAKE_SIZE          2
#macro SCRIBBLE_ANIM_DEFAULT_SHAKE_SPEED         0.4

#macro SCRIBBLE_ANIM_DEFAULT_RAINBOW_WEIGHT      0.5
#macro SCRIBBLE_ANIM_DEFAULT_RAINBOW_SPEED       0.01

#macro SCRIBBLE_ANIM_DEFAULT_WOBBLE_ANGLE        40
#macro SCRIBBLE_ANIM_DEFAULT_WOBBLE_FREQ         0.15

#macro SCRIBBLE_ANIM_DEFAULT_PULSE_SCALE         0.4
#macro SCRIBBLE_ANIM_DEFAULT_PULSE_SPEED         0.1

#macro SCRIBBLE_ANIM_DEFAULT_WHEEL_SIZE          1
#macro SCRIBBLE_ANIM_DEFAULT_WHEEL_FREQUENCY     0.5
#macro SCRIBBLE_ANIM_DEFAULT_WHEEL_SPEED         0.2

#macro SCRIBBLE_ANIM_DEFAULT_CYCLE_SPEED         0.5
#macro SCRIBBLE_ANIM_DEFAULT_CYCLE_SATURATION    180
#macro SCRIBBLE_ANIM_DEFAULT_CYCLE_VALUE         255

#macro SCRIBBLE_ANIM_DEFAULT_JITTER_MIN_SCALE    0.7
#macro SCRIBBLE_ANIM_DEFAULT_JITTER_MAX_SCALE    1.2
#macro SCRIBBLE_ANIM_DEFAULT_JITTER_SPEED        0.4

#macro SCRIBBLE_ANIM_DEFAULT_BLINK_ON_DURATION   50
#macro SCRIBBLE_ANIM_DEFAULT_BLINK_OFF_DURATION  50
#macro SCRIBBLE_ANIM_DEFAULT_BLINK_TIME_OFFSET   0