function __scribble_font_convert_msdf_to_yy(_resource_name, _json_filename, _sprite_filename)
{
    var _output_root = {
        hinting: 0,
        glyphOperations: 0,
        interpreter: 0,
        pointRounding: 0,
        applyKerning: 0,
        fontName: "Scribble MSDF",
        styleName: "MSDF",
        size: 12.0,
        bold: false,
        italic: false,
        charset: 0,
        AntiAlias: 0,
        first: 0,
        last: 0,
        sampleText: "Generated by Scribble",
        includeTTF: false,
        TTFName: "",
        textureGroupId: {
            name: "Default",
            path: "texturegroups/Default",
        },
        ascenderOffset: 0,
        glyphs: {},
        kerningPairs: [],
        ranges: [
            {
                lower : 32,
                upper : 32,
            }
        ],
        regenerateBitmap: false,
        canGenerateBitmap: false,
        maintainGms1Font: false,
        parent : {
            name : "Fonts",
            path : "folders/Fonts.yy",
        },
        resourceVersion: "1.0",
        name: _resource_name,
        tags : [],
        resourceType: "GMFont",
    };
    
    var _json_buffer = buffer_load(_json_filename);
    if (_json_buffer < 0) __scribble_error("Could not find \"", _json_filename, "\"\nPlease add it to the project's Included Files");
    
    var _json_string = buffer_read(_json_buffer, buffer_text);
    buffer_delete(_json_buffer);
    var _json = json_decode(_json_string); //TODO - Replace with json_parse()
    
    var _metrics_map     = _json[? "metrics"];
    var _json_glyph_list = _json[? "glyphs" ];
    var _atlas_map       = _json[? "atlas"  ];
    
    var _em_size      = _atlas_map[? "size"         ];
    var _msdf_pxrange = _atlas_map[? "distanceRange"];
    var _atlas_height = _atlas_map[? "height"       ];
    
    var _json_line_height = _em_size*_metrics_map[? "lineHeight"];
    
    var _i = 0;
    var _size = ds_list_size(_json_glyph_list);
    repeat(_size)
    {
        var _json_glyph_map = _json_glyph_list[| _i];
        var _plane_map = _json_glyph_map[? "planeBounds"];
        var _atlas_map = _json_glyph_map[? "atlasBounds"];
        
        var _ord  = _json_glyph_map[? "unicode"];
        var _char = chr(_ord);
        
        if (_atlas_map != undefined)
        {
            var _tex_l = _atlas_map[? "left"] + 1;
            var _tex_t = _atlas_height - _atlas_map[? "top"] + 1; //This atlas format is weird
            var _tex_r = _atlas_map[? "right"] - 1;
            var _tex_b = _atlas_height - _atlas_map[? "bottom"] - 1;
        }
        else
        {
            var _tex_l = 0;
            var _tex_t = 0;
            var _tex_r = 0;
            var _tex_b = 0;
        }
        
        var _w = _tex_r - _tex_l;
        var _h = _tex_b - _tex_t;
        
        if (_plane_map != undefined)
        {
            var _xoffset  = _em_size*_plane_map[? "left"];
            var _yoffset  = _em_size - _em_size*_plane_map[? "top"]; //So, so weird
            var _xadvance = round(_em_size*_json_glyph_map[? "advance"]); //_w - _msdf_pxrange - round(_em_size*_plane_map[? "left"]);
        }
        else
        {
            var _xoffset  = 0;
            var _yoffset  = 0;
            var _xadvance = round(_em_size*_json_glyph_map[? "advance"]);
        }
        
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.CHARACTER   ] = _char;
        //
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.ORD         ] = _ord;
        //
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.X_OFFSET    ] = _xoffset;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.Y_OFFSET    ] = _yoffset;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.WIDTH       ] = _w;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.HEIGHT      ] = _h;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.FONT_HEIGHT ] = _json_line_height;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.SEPARATION  ] = _xadvance;
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.FONT_SCALE  ] = 1;
        //
        //_font_glyph_data_grid[# _i, SCRIBBLE_GLYPH.MSDF_PXRANGE] = _msdf_pxrange;
        //
        //_font_glyphs_map[? _ord] = _i;
        
        ++_i;
    }
    
    var _output_string = json_stringify(_output_root);
    var _output_buffer = buffer_create(string_byte_length(_output_string), buffer_fixed, 1);
    buffer_write(_output_buffer, buffer_text, _output_string);
    buffer_save(_output_buffer, _resource_name + ".yy");
    buffer_delete(_output_buffer);
    
    ds_map_destroy(_json);
}