// Default font is set by scribble_font_set_default()

#macro SCRIBBLE_DEFAULT_COLOR               c_white
#macro SCRIBBLE_DEFAULT_HALIGN              fa_left
#macro SCRIBBLE_DEFAULT_VALIGN              fa_top
#macro SCRIBBLE_DEFAULT_SPRITE_SPEED        0.1      //The default animation speed for sprites inserted into text
#macro SCRIBBLE_DEFAULT_DELAY_DURATION      450      //Default duration of the [delay] command, in milliseconds

#macro SCRIBBLE_DEFAULT_WAVE_SIZE           4
#macro SCRIBBLE_DEFAULT_WAVE_FREQUENCY      50
#macro SCRIBBLE_DEFAULT_WAVE_SPEED          0.2

#macro SCRIBBLE_DEFAULT_SHAKE_SIZE          2
#macro SCRIBBLE_DEFAULT_SHAKE_SPEED         0.4

#macro SCRIBBLE_DEFAULT_RAINBOW_WEIGHT      0.5
#macro SCRIBBLE_DEFAULT_RAINBOW_SPEED       0.01

#macro SCRIBBLE_DEFAULT_WOBBLE_ANGLE        40
#macro SCRIBBLE_DEFAULT_WOBBLE_FREQ         0.15

#macro SCRIBBLE_DEFAULT_PULSE_SCALE         0.4
#macro SCRIBBLE_DEFAULT_PULSE_SPEED         0.1

#macro SCRIBBLE_DEFAULT_WHEEL_SIZE          1
#macro SCRIBBLE_DEFAULT_WHEEL_FREQUENCY     0.5
#macro SCRIBBLE_DEFAULT_WHEEL_SPEED         0.2

#macro SCRIBBLE_DEFAULT_CYCLE_SPEED         0.5
#macro SCRIBBLE_DEFAULT_CYCLE_SATURATION    180
#macro SCRIBBLE_DEFAULT_CYCLE_VALUE         255

#macro SCRIBBLE_DEFAULT_JITTER_MIN_SCALE    0.7
#macro SCRIBBLE_DEFAULT_JITTER_MAX_SCALE    1.2
#macro SCRIBBLE_DEFAULT_JITTER_SPEED        0.4

#macro SCRIBBLE_DEFAULT_BLINK_ON_DURATION   50
#macro SCRIBBLE_DEFAULT_BLINK_OFF_DURATION  50
#macro SCRIBBLE_DEFAULT_BLINK_TIME_OFFSET   0